<hr style="border-width:2px;border-color:#75DFC1">
<h1 style = "text-align:center" > Statistiques exploratoires </h1> 
<h2 style = "text-align:center"> Analyse descriptive des variables qualitatives d'un jeu de données </h2> 
<hr style="border-width:2px;border-color:#75DFC1">

### Contexte et objectif

> L'analyse des variables qualitatives est une étape importante dans la compréhension des données. Elles sont souvent plus difficiles à manipuler et il est important d'observer leur relation avec les variables numériques. Elles livrent souvent des informations précieuses sur l'intéraction entre les variables dans le jeu de données.

> L'objectif de ce module est d'arriver à déterminer les modalités d'une variable qualitative et l'importance de chacune. Également, ce module vous permettra de vous familiariser avec des méthodes simples de gestion de données.

> Commençons par la phase d'importation des packages.

* Importer les packages **pandas** et **numpy**.

* Charger dans un tableau nommé *data* les données situées dans le fichier *'crowdfunding.csv'* en mettant la **première colonne en indice** et afficher les 5 premières lignes.

In [2]:
# Insérez votre code ici

,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country
ID,,,,,,,,,,,
1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB
1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US
1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US
1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US
1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,failed,14,US

* Déterminer les variables catégorielles et les stocker dans un tableau **`cat_data`**.

<div class="alert alert-info">
<i class="fa fa-info-circle"></i> &emsp; 
On pourra s'aider de la fonction pandas.DataFrame.select_dtypes() et de l'attribut *include* auquel on renseignera une liste du ou des type(s) qu'on souhaite garder (ici 'O').
</div>

In [6]:
# Insérez votre code ici

,name,category,main_category,currency,deadline,launched,state,country
ID,,,,,,,,
1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,2015-08-11 12:12:28,failed,GB
1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,2017-09-02 04:43:57,failed,US
1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,2013-01-12 00:20:50,failed,US
1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,2012-03-17 03:24:11,failed,US
1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,2015-07-04 08:35:03,failed,US

> L'analyse descriptive des variables qualitatives font appel à d'autres outils de pandas. Une première question qu'on doit se poser quand on fait face à ce type de données est de se demander quelles sont les modalités de chaque variable et comment se répartissent-elles ?

* Afficher les modalités ainsi que leur fréquence de la variable **main_category**.
* Quelle est la variable la plus fréquente ?


> <div class="alert alert-info">
<i class="fa fa-info-circle"></i> &emsp; 
On pourra s'aider de pandas.Series.value_counts()
</div>

> <div class="alert alert-danger">
<i class='fa fa-exclamation-triangle'></i> &emsp; 
value_counts ne s'utilise pas sur des objets de type DataFrame
</div>

In [8]:
# Insérez votre code ici

/home/ubuntu/virtualenvs/python3/lib/python3.6/site-packages/pandas/compat/_optional.py:106: UserWarning: Pandas requires version '2.6.2' or newer of 'numexpr' (version '2.6.1' currently installed).
  warnings.warn(msg, UserWarning)

Film & Video    0.1695
Music           0.1396
Publishing      0.1026
Games           0.0977
Design          0.0832
Technology      0.0815
Art             0.0778
Food            0.0612
Fashion         0.0587
Theater         0.0290
Comics          0.0287
Photography     0.0272
Crafts          0.0232
Journalism      0.0110
Dance           0.0091
Name: main_category, dtype: float64

> **value_counts** est couramment utilisé pour visualiser très rapidement les modalités d'une variable qualitative.
> On peut également retrouver très facilement la modalité la plus fréquente d'une variable qualitative : la méthode **mode** permet de récupérer l'élément le plus fréquent à l'intérieur d'une pandas.Series.

* Utiliser la méthode **mode** pour récupérer la modalité la plus fréquente de **main_category**.
* Vérifier que cela correspond bien avec le **value_counts** exécuté précédemment.

In [9]:
# Insérez votre code ici

0    Film & Video
dtype: object

> Dans ce jeu de données, nous disposons d'une variable binaire **state** qui renseigne sur la réussite ou l'échec de la collecte. Ces variables sont généralement très intéressantes à étudier et livrent des informations précieuses sur les jeux de données. Il est important de bien les identifier et d'étudier dans un premier temps la fréquence des modalités.

* Afficher les fréquences des modalités de la variable **state**.

In [10]:
# Insérez votre code ici

failed        0.6435
successful    0.3565
Name: state, dtype: float64

> On constate que 64% des collectes ont échouées. Ce chiffre a peu d'intérêt si on ne le met pas en perspective avec le montant des objectifs fixés. L'objectif est de faire une sorte de cartographie : 64% des collectes ont échoué mais quelles collectes sont concernées ? Les grosses ? Les petites ? Les deux ?

> Pour avoir une première idée, il est nécessaire de se munir du jeu de données complet *data* et d'utiliser les outils **groupby** et **agg** qui s'utilisent aussi bien sur les DataFrame que sur les Series.

* Tout d'abord dans une nouvelle variable **goal_classes**, découpez les montants cibles (**goal**) en 4 classes distinctes avec pour labels 0, 1, 2, 3 selon les 3 quantiles de la nouvelle variable créée.
<br><br>
<div class="alert alert-info">
<i class="fa fa-info-circle"></i> &emsp;
Il est fortement conseillé d'utiliser <strong> pandas.qcut() </strong>
</div>

In [13]:
# Insérez votre code ici

,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,goal_classes
ID,,,,,,,,,,,,
1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0
1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,3
1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,3
1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1
1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,failed,14,US,3

* En utilisant **groupby** et **agg**, stocker dans **`state_summary`** les montants cibles (**goal**) en fonction des variables **state** et **goal_classes**.
<br><br>
<div class="alert alert-info">
<i class="fa fa-info-circle"></i> &emsp;
    <i>Exemple d'utilisation</i> : <code style="background-color:transparent;color:inherit"> df.groupby(['Age','sex']).agg({'salaire':'sum'}]</code>
</div>

In [17]:
# Insérez votre code ici

                                 goal
goal_classes state
0            failed      1.446860e+06
             successful  1.200423e+06
1            failed      5.565180e+06
             successful  3.491960e+06
2            failed      1.618726e+07
             successful  8.578267e+06
3            failed      3.338452e+08
             successful  2.296345e+07

> Le montant en lui-même ne nous apporte aucune information. Il faut l'affiner en le présentant par exemple sous forme de pourcentage.

* Exécuter la cellule de code suivante (**une seule fois**).

In [18]:
for i in [0,1,2,3]:
    tot = data[data['goal_classes'] == i].sum()
    state_summary.loc[i,'failed'] = state_summary.loc[i,'failed']/tot
    state_summary.loc[i,'successful'] = state_summary.loc[i,'successful']/tot

> **`state_summary`** affiche désormais les pourcentages de réussite ou d'échec suivant les quartiles où on se place.

* Que remarquez-vous ?

In [19]:
# Insérez votre code ici

                             goal
goal_classes state
0            failed      0.546545
             successful  0.453455
1            failed      0.614452
             successful  0.385548
2            failed      0.653621
             successful  0.346379
3            failed      0.935642
             successful  0.064358

* Ajouter à **`state_summary`** l'information relative au champ *backers*.

In [22]:
# Insérez votre code ici

                             goal  backers
goal_classes state
0            failed      0.546545     5898
             successful  0.453455    64611
1            failed      0.614452    15766
             successful  0.385548   114950
2            failed      0.653621    25349
             successful  0.346379   244585
3            failed      0.935642    73703
             successful  0.064358   561803

> De manière purement analytique, nous avons décelé une information importante pour réussir son objectif de cagnotte : statistiquement, il semble qu'il ne faille pas fixer un objectif trop élevé à atteindre. Également, on remarquera que les campagnes qui sont un succès semblent réunir un nombre plus important de contributeurs. Question légitime que l'on peut se poser : Peut-on avoir une idée du montant objectif (**goal**) à fixer pour optimiser ses chances de réussir ?

* Reprendre *data* et toujours en utilisant **groupby**,**agg** exprimer les montants cibles (**goal**) médians, moyens, minimum et maximum en fonction de **state** dans un DataFrame *target_goal*.

In [24]:
# Insérez votre code ici

              goal
            median          mean  min         max
state
failed      7500.0  55484.773330  1.0  40000000.0
successful  4000.0  10163.843759  1.0    950000.0

* En vous appuyant sur le module précédent (hétérogénéité, étendue des variables), est-il possible selon vous d'avoir une idée précise à priori du montant objectif à fixer pour réussir une collecte ?

In [25]:
# Insérez votre code ici

              goal
            median          mean  min         max
state
failed      7500.0  55484.773330  1.0  40000000.0
successful  4000.0  10163.843759  1.0    950000.0

> Il reste une dernière question importante à traiter : vers quelle(s) catégorie(s) dois-je me tourner si je souhaite maximiser ma collecte indépendamment de la réussir ou non ? 
> Pour répondre à cette question on utilisera les variables **main_category**,**pledged**,**backers**.

* En vous servant du module précédent et de ce qu'on a vu dans celui actuel, proposez une solution pour répondre à la question.
<br><br>
<div class="alert alert-info">
<i class="fa fa-info-circle"></i> &emsp;
On pourra regarder la collecte versée par les contributeurs pour chaque catégorie.
</div>

In [28]:
# Insérez votre code ici

main_category
Art              70.640679
Comics           50.230698
Crafts           53.180757
Dance            70.917226
Design          105.571192
Fashion          88.932187
Film & Video    102.688610
Food            109.382333
Games           103.423747
Journalism       46.419320
Music            74.350669
Photography      94.558708
Publishing       77.004361
Technology      143.717118
Theater          82.490932
Name: ratio_pledge_backers, dtype: float64